<Project>
  <PropertyGroup>
    <BuildNumber Condition="'$(BuildNumber)' == ''">0.0</BuildNumber>
    <Build_BuildNumber>$(BuildNumber)</Build_BuildNumber>
    <MajorVersion>9.57</MajorVersion>
    <Version>$(MajorVersion).$(Build_BuildNumber)</Version>
  </PropertyGroup>

  <PropertyGroup>
    <Publisher Condition="'$(Publisher)' == ''">CN=Contoso Ltd.</Publisher>
    <PublisherDisplayName Condition="'$(PublisherDisplayName)' == ''">Contoso Ltd.</PublisherDisplayName>
  </PropertyGroup>

  <PropertyGroup>
    <!-- Workaround for breaking changes in PackageDefinitions metadata. https://github.com/dotnet/sdk/issues/30809 -->
    <!-- TODO: avoid of the PackageDefinitions usage. -->
    <EmitLegacyAssetsFileItems>true</EmitLegacyAssetsFileItems>
  </PropertyGroup>

  <PropertyGroup>
    <CommerceSdkPackagesVersion>[9.57.*-*,9.58)</CommerceSdkPackagesVersion>
    <CommercePosPackagesVersion>[9.57.*-*,9.58)</CommercePosPackagesVersion>
    <CommerceChannelPackagesVersion>[9.57.*-*,9.58)</CommerceChannelPackagesVersion>
    <CommerceHwsPackagesVersion>[9.57.*-*,9.58)</CommerceHwsPackagesVersion>
    <CommerceToolsPackagesVersion>[10.38.*-*,10.39)</CommerceToolsPackagesVersion>
    <CommercePaymentsPackagesVersion>[10.57.*-*,10.58)</CommercePaymentsPackagesVersion>
    <TypeScriptPackagesVersion>4.7.*</TypeScriptPackagesVersion>
    <MauiVersion>9.0.110</MauiVersion>
  </PropertyGroup>
</Project>
