<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\CustomizationPackage.props" />
  <!-- Override the default CustomizationPackage.props if it exists in the solution directory. -->
  <Import Project="$(SolutionDir)CustomizationPackage.props" Condition="Exists('$(SolutionDir)CustomizationPackage.props')" />

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <OutputLocation>$(OutputPath)</OutputLocation>
    <OutputLocation Condition="'$(OutputLocation)' == ''">$(MSBuildProjectDirectory)\bin\$(Configuration)\$(TargetFramework)</OutputLocation>
  </PropertyGroup>

  <ItemGroup>
    <!-- SQLite extensions build is only supported on Windows Platform. -->
    <PackageReference Include="Microsoft.Dynamics.Commerce.Sdk.ChannelDatabase" Version="$(CommerceSdkPackagesVersion)" Condition="$([System.OperatingSystem]::IsWindows())" />
  </ItemGroup>
</Project>