IF (SELECT OBJECT_ID('[ext].CONTOSO_CANNOTBECONVERTEDAUTOMATICALLY_TOSQLITE_VIEW1')) IS NOT NULL
    DROP VIEW [ext].CONTOSO_CANNOTBECONVERTEDAUTOMATICALLY_TOSQLITE_VIEW1
GO

CREATE VIEW [ext].CONTOSO_CANNOTBECONVERTEDAUTOMATICALLY_TOSQLITE_VIEW1 AS
(
    SELECT COALESCE((SELECT TOP 1 IMAGEURL FROM [ax].[RETAILMEDIATEMPLATE] WHERE MASTERENTITYTYPE = 13), N'') AS CATEGORYDEFAULTIMAGETEMPLATE
)

GO

GRANT SELECT ON [ext].CONTOSO_CANNOTBECONVERTEDAUTOMATICALLY_TOSQLITE_VIEW1 TO [UsersRole];
GO