IF (SELECT OBJECT_ID('[ext].CONTOSO_CANNOTBECONVERTED_AUTOMATICALLYTOSQLITE_VIEW2')) IS NOT NULL
    DROP VIEW [ext].CONTOSO_CANNOTBECONVERTED_AUTOMATICALLYTOSQLITE_VIEW2
GO

CREATE VIEW [ext].CONTOSO_CANNOTBECONVERTED_AUTOMATICALLYTOSQLITE_VIEW2 AS
(
    SELECT
        rst.STAFFID,
        rst.NAMEONRECEIPT,
        rst.PASSWORDLASTCHANGEDDATETIME,
        dpt.NAME,
        rmr.RESOURCEURL AS IMAGE,
        rst.CULTURENAME,
        'data:image/jpeg;base64,' + CAST(N'' AS XML).value('xs:base64Binary(xs:hexBinary(sql:column("[rmr].[RESOURCEBLOB]")))', 'NVARCHAR(MAX)') AS [DEFAULTIMAGE]
    FROM  [ax].RETAILSTAFFTABLE rst
    INNER JOIN [ax].HCMWORKER worker ON [rst].STAFFID = [worker].PERSONNELNUMBER
    INNER JOIN [ax].DIRPARTYTABLE dpt ON [worker].PERSON = [dpt].RECID
    LEFT OUTER JOIN [ax].RETAILMEDIAANDMASTERENTITYRELATION rmamer ON [worker].RECID = [rmamer].MASTERENTITYRECID AND [rmamer].ISDEFAULT = 1 AND [rmamer].MASTERENTITYTYPE = 15  -- MasterEntityType = Employee.
    LEFT OUTER JOIN [ax].RETAILMEDIARESOURCE rmr ON [rmr].RESOURCEID = [rmamer].MEDIARESOURCEID
)

GO

GRANT SELECT ON [ext].CONTOSO_CANNOTBECONVERTED_AUTOMATICALLYTOSQLITE_VIEW2 TO [UsersRole];
GO