CREATE VIEW IF NOT EXISTS ext_CONTOSO_CANNOTBECONVERTEDAUTOMATICALLY_TOSQLITE_VIEW1
AS
    SELECT
        COALESCE((SELECT IMAGEURL FROM ax_RETAILMEDIATEMPLATE WHERE MASTERENTITYTYPE = 11 LIMIT 1), '') AS CATALOGDEFAULTIMAGETEMPLATE