<Project Sdk="Microsoft.NET.Sdk.Razor">
  <Import Project="..\CustomizationPackage.props" />

  <PropertyGroup>
    <TargetFrameworks>net10.0-android;net10.0-ios;net10.0-maccatalyst</TargetFrameworks>
    <UseMaui>true</UseMaui>
    <OutputType>Exe</OutputType>
    <RootNamespace>Contoso.StoreCommerce.MobileApp</RootNamespace>
    <AssemblyName>Contoso.StoreCommerce.MobileApp</AssemblyName>

    <!-- Display name -->
    <ApplicationTitle Condition="$(ApplicationTitle) == ''">Contoso Store Commerce</ApplicationTitle>

    <!-- App Identifier -->
    <ApplicationId Condition="$(ApplicationId) == ''">contoso.storecommerce.mobileapp</ApplicationId>

    <!-- Versions -->
    <ApplicationDisplayVersion>$(PackageVersion)</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>

    <!-- Prevent extension assemblies from being trimmed on iOS/MacCatalyst builds -->
    <UseInterpreter Condition="($(TargetFramework.Contains('-ios')) or $(TargetFramework.Contains('-maccatalyst'))) and '$(Configuration)' == 'Release'">true</UseInterpreter>

    <!-- Prevent extension assemblies from being embedded in the APK on Android Release builds -->
    <Optimize Condition="$(TargetFramework.Contains('-android')) and '$(Configuration)' == 'Release'">false</Optimize>
    <EmbedAssembliesIntoApk Condition="$(TargetFramework.Contains('-android')) and '$(Configuration)' == 'Release'">false</EmbedAssembliesIntoApk>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Dynamics.Commerce.Sdk.StoreCommerce.Mobile" Version="$(CommerceSdkPackagesVersion)" />
    <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="$(MauiVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\StoreCommerceApp\ChannelDatabase\Contoso.StoreCommercePackagingSample.ChannelDatabase.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\..\StoreCommerceSamples\PosExtensionSamples\CommerceRuntime\Contoso.PosExtensions.CommerceRuntime.csproj" />
    <ProjectReference Include="..\..\..\StoreCommerceSamples\PosExtensionSamples\Pos\Contoso.PosExtensions.Pos.csproj" />
    <ProjectReference Include="..\..\..\HardwareStationSamples\PaymentDevice\Contoso.PaymentDeviceSample.csproj" />
    <ProjectReference Include="..\..\..\HardwareStationSamples\PeripheralCustomizations\Contoso.PeripheralCustomizations.csproj" />
  </ItemGroup>
</Project>